<?php

namespace Database\Seeders;

use App\Models\CategoriaArticulo;
use App\Models\ArticuloAsesoria;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AsesoriaSeeder extends Seeder
{
    public function run(): void
    {
        CategoriaArticulo::query()->delete();
        ArticuloAsesoria::query()->delete();

        DB::statement('ALTER TABLE tbl_asesoria_categoria AUTO_INCREMENT = 1');
        DB::statement('ALTER TABLE tbl_asesoria_articulo AUTO_INCREMENT = 1');

        $categorias = [
            [
                'nombre' => 'Legal y normativa',
                'icono' => 'bi bi-bank2',
                'orden' => 1,
                'articulos' => [
                    [
                        'titulo' => '¿Cuáles son los derechos básicos del inquilino?',
                        'contenido' => '<p>Como inquilino, tienes derechos fundamentales recogidos en la Ley de Arrendamientos Urbanos (LAU):</p><ul><li><strong>Uso pacífico de la vivienda:</strong> No puedes ser desalojado sin una causa legal y sin seguir el procedimiento judicial correspondiente.</li><li><strong>Prórroga obligatoria:</strong> Tienes derecho a permanecer en la vivienda durante los primeros 5 años (o 7 si el arrendador es persona jurídica), siempre que cumplas con tus obligaciones.</li><li><strong>Reparaciones urgentes:</strong> El arrendador está obligado a realizar las reparaciones necesarias para mantener la vivienda en condiciones habitables.</li><li><strong>No discriminación:</strong> No pueden negarte el alquiler por razones de origen, religión, orientación sexual o situación familiar.</li><li><strong>Privacidad:</strong> El arrendador no puede entrar en la vivienda sin tu permiso, salvo casos de emergencia.</li><li><strong>Devolución de la fianza:</strong> Al finalizar el contrato, tienes derecho a que te devuelvan la fianza si no hay daños en la vivienda.</li></ul><p>Si consideras que alguno de tus derechos está siendo vulnerado, puedes presentar una reclamación ante la Agencia de Vivienda de tu comunidad autónoma o acudir a los tribunales.</p>',
                        'destacado' => true,
                        'orden_faq' => 1,
                    ],
                    [
                        'titulo' => '¿Qué obligaciones legales tiene el arrendador?',
                        'contenido' => '<p>El arrendador debe cumplir con una serie de obligaciones establecidas por ley:</p><ul><li><strong>Entregar la vivienda en condiciones:</strong> La vivienda debe estar en estado óptimo de habitabilidad, con los suministros básicos funcionando (agua, luz, gas).</li><li><strong>Realizar reparaciones necesarias:</strong> Todas las reparaciones estructurales y de mantenimiento mayor corren por cuenta del arrendador, salvo que el deterioro sea por mal uso del inquilino.</li><li><strong>Respetar la duración del contrato:</strong> No puede forzar la salida del inquilino antes de que finalice el período mínimo legal de 5 años.</li><li><strong>Depositar la fianza:</strong> Está obligado a depositar la fianza en el organismo correspondiente de su comunidad autónoma (IVIMA en Madrid, INCASÒL en Cataluña, etc.).</li><li><strong>Declarar los ingresos:</strong> Debe declarar las rentas percibidas en su declaración de IRPF.</li><li><strong>No realizar visitas sin consentimiento:</strong> No puede entrar en la vivienda alquilada sin autorización expresa del inquilino.</li></ul><p>El incumplimiento de estas obligaciones puede dar lugar a reclamaciones por parte del inquilino e incluso a la rescisión del contrato.</p>',
                    ],
                    [
                        'titulo' => '¿Qué es la Ley de Vivienda 2023 y cómo me afecta?',
                        'contenido' => '<p>La Ley por el Derecho a la Vivienda (Ley 12/2023), aprobada en mayo de 2023, introdujo cambios significativos en el mercado del alquiler:</p><ul><li><strong>Límite a la subida de rentas:</strong> Durante 2023 y 2024, la actualización de la renta quedó limitada al 2% y al 3% respectivamente, en lugar del IPC general.</li><li><strong>Nuevo índice de referencia:</strong> Se creó un nuevo índice de actualización anual que sustituye al IPC a partir de 2025, con el objetivo de que las subidas sean más moderadas.</li><li><strong>Gastos de gestión inmobiliaria:</strong> Los gastos de gestión inmobiliaria y formalización del contrato correrán a cargo del arrendador (no del inquilino como ocurría antes).</li><li><strong>Declaración de zonas tensionadas:</strong> Las comunidades autónomas pueden declarar zonas de mercado tensionado donde se aplicarán límites adicionales a los precios del alquiler.</li><li><strong>Protección de inquilinos vulnerables:</strong> Se refuerzan los mecanismos de protección para inquilinos en situación de vulnerabilidad, con suspensión de desahucios en ciertos casos.</li></ul><p>Esta ley varía en su aplicación según cada comunidad autónoma, por lo que es recomendable consultar la normativa específica de tu región.</p>',
                    ],
                    [
                        'titulo' => 'Protección de datos personales en el alquiler',
                        'contenido' => '<p>La gestión de un alquiler implica el tratamiento de datos personales tanto del inquilino como del arrendador. Es importante conocer tus derechos bajo el RGPD (Reglamento General de Protección de Datos):</p><ul><li><strong>Datos mínimos necesarios:</strong> El arrendador solo puede recopilar los datos estrictamente necesarios para la formalización del contrato (DNI, datos de contacto, información laboral básica).</li><li><strong>Consentimiento:</strong> Debes dar tu consentimiento explícito para el tratamiento de tus datos personales.</li><li><strong>Finalidad limitada:</strong> Tus datos no pueden ser utilizados para fines distintos a los del contrato de alquiler (por ejemplo, no pueden enviarte publicidad sin tu permiso).</li><li><strong>Derecho de supresión:</strong> Una vez finalizado el contrato, puedes solicitar que el arrendador elimine tus datos personales, salvo que exista una obligación legal de conservarlos.</li><li><strong>Cesión de datos:</strong> El arrendador no puede compartir tus datos con terceros sin tu autorización.</li></ul><p>Si detectas un uso indebido de tus datos personales, puedes presentar una reclamación ante la Agencia Española de Protección de Datos (AEPD).</p>',
                    ],
                ],
            ],
            [
                'nombre' => 'Contratos de alquiler',
                'icono' => 'bi bi-file-earmark-text',
                'orden' => 2,
                'articulos' => [
                    [
                        'titulo' => '¿Qué debe incluir un contrato de alquiler?',
                        'contenido' => '<p>Un contrato de alquiler debe contener, como mínimo, los siguientes elementos para ser válido:</p><ul><li><strong>Identificación de las partes:</strong> Datos completos del arrendador y del inquilino (DNI/NIE, nombre completo, domicilio).</li><li><strong>Descripción de la vivienda:</strong> Dirección, superficie, distribución y estado general del inmueble.</li><li><strong>Duración del contrato:</strong> Fecha de inicio y duración acordada. Por defecto, la LAU establece un mínimo de 5 años (7 si el arrendador es persona jurídica).</li><li><strong>Renta mensual:</strong> Importe exacto, forma de pago y fecha de vencimiento cada mes.</li><li><strong>Fianza legal:</strong> Equivalente a una mensualidad de renta, depositada en el organismo autonómico correspondiente.</li><li><strong>Gastos y suministros:</strong> Quién se hace cargo de cada suministro (agua, luz, gas, comunidad).</li><li><strong>Cláusulas adicionales:</strong> Cualquier pacto entre ambas partes que no contradiga la ley (mascotas, subarriendo, etc.).</li></ul><p>Es recomendable que el contrato se firme por duplicado y que cada parte conserve una copia. También es aconsejable realizar un inventario de mobiliario y electrodomésticos si la vivienda se entrega amueblada.</p>',
                        'destacado' => true,
                        'orden_faq' => 2,
                    ],
                    [
                        'titulo' => 'Duración del contrato: ¿5 o 7 años?',
                        'contenido' => '<p>La duración mínima del contrato de alquiler depende de quién sea el arrendador:</p><ul><li><strong>Arrendador persona física:</strong> El contrato tiene una duración mínima de <strong>5 años</strong>. Durante este período, el inquilino tiene derecho a permanecer en la vivienda cumpliendo con sus obligaciones, y el arrendador no puede rescindir el contrato salvo causas graves (impago, necesidad de vivienda propia acreditada, etc.).</li><li><strong>Arrendador persona jurídica:</strong> La duración mínima se amplía a <strong>7 años</strong> si el propietario es una empresa o sociedad.</li></ul><p><strong>Prórroga tácita:</strong> Una vez transcurrido el plazo mínimo, si ninguna de las partes comunica su intención de no renovar, el contrato se prorroga automáticamente por anualidades hasta un máximo de 3 años adicionales (prórroga legal).</p><p><strong>Desistimiento del inquilino:</strong> El inquilino puede renunciar al contrato antes de cumplir el año de duración, indemnizando al arrendador con una mensualidad por cada año que falte por cumplir.</p>',
                    ],
                    [
                        'titulo' => 'Renovación y actualización del contrato',
                        'contenido' => '<p>La renovación del contrato de alquiler puede producirse de varias formas:</p><ul><li><strong>Prórroga obligatoria (legal):</strong> Al cumplirse los 5 años (o 7 para persona jurídica), el contrato se prorroga automáticamente por anualidades hasta un máximo de 3 años si ninguna de las partes notifica lo contrario.</li><li><strong>Prórroga voluntaria:</strong> Una vez agotada la prórroga legal (8 o 10 años en total), las partes pueden acordar una nueva prórroga en los términos que deseen.</li><li><strong>Nuevo contrato:</strong> Al finalizar el período total, se puede firmar un nuevo contrato con nuevas condiciones.</li></ul><p><strong>Actualización de la renta:</strong> Durante la vigencia del contrato, la renta puede actualizarse anualmente según el índice que las partes hayan acordado (IPC, IGC o el nuevo índice de referencia).</p><p>Es importante que cualquier cambio en las condiciones del contrato se realice por escrito y sea firmado por ambas partes para evitar futuros conflictos.</p>',
                    ],
                    [
                        'titulo' => 'Cláusulas abusivas más comunes en contratos de alquiler',
                        'contenido' => '<p>Algunas cláusulas que aparecen frecuentemente en contratos de alquiler pueden ser consideradas abusivas y, por tanto, nulas:</p><ul><li><strong>Prohibición total de mascotas:</strong> Salvo que existan razones objetivas (alergias documentadas, normativa de la comunidad), esta cláusula puede ser declarada nula si limita desproporcionadamente el derecho a la vida privada del inquilino.</li><li><strong>Renuncia a la prórroga obligatoria:</strong> El inquilino no puede renunciar a su derecho a los 5/7 años mínimos de contrato.</li><li><strong>Imputación de todos los gastos al inquilino:</strong> Los gastos de comunidad y suministros deben especificarse claramente; no se puede cargar al inquilino gastos extraordinarios no previstos.</li><li><strong>Penalización por impago desproporcionada:</strong> Las cláusulas penales deben ser proporcionales al daño causado.</li><li><strong>Autorización para entrar en la vivienda sin previo aviso:</strong> Cualquier visita del arrendador debe ser acordada previamente con el inquilino.</li></ul><p>Si tienes dudas sobre alguna cláusula de tu contrato, desde SpotStay te recomendamos consultar con un profesional legal antes de firmar.</p>',
                    ],
                    [
                        'titulo' => 'Rescisión del contrato de alquiler',
                        'contenido' => '<p>La rescisión del contrato de alquiler puede producirse por diferentes causas:</p><p><strong>Por parte del inquilino:</strong></p><ul><li><strong>Desistimiento:</strong> El inquilino puede rescindir el contrato antes del plazo mínimo, indemnizando con una mensualidad por año pendiente (solo aplica durante el primer año).</li><li><strong>Incumplimiento del arrendador:</strong> Si el arrendador no realiza reparaciones necesarias o vulnera los derechos del inquilino.</li></ul><p><strong>Por parte del arrendador:</strong></p><ul><li><strong>Impago de la renta:</strong> Es la causa más común. Requiere un procedimiento de desahucio judicial.</li><li><strong>Necesidad de vivienda propia:</strong> El arrendador puede recuperar la vivienda si la necesita para sí mismo o para familiares directos, pero debe acreditarlo y comunicarlo con 2 meses de antelación.</li><li><strong>Obras de rehabilitación:</strong> Si se van a realizar obras mayores que impidan el uso de la vivienda.</li></ul><p>En todos los casos, la rescisión debe comunicarse por escrito y respetar los plazos establecidos en el contrato y en la ley.</p>',
                    ],
                ],
            ],
            [
                'nombre' => 'Pagos, rentas y fianzas',
                'icono' => 'bi bi-cash-stack',
                'orden' => 3,
                'articulos' => [
                    [
                        'titulo' => '¿Cómo funciona el pago del alquiler?',
                        'contenido' => '<p>El pago del alquiler es la obligación principal del inquilino y debe realizarse según lo acordado en el contrato:</p><ul><li><strong>Plazo de pago:</strong> La renta se paga por meses anticipados, normalmente dentro de los primeros 7 días de cada mes, salvo que el contrato especifique otra fecha.</li><li><strong>Medios de pago:</strong> Lo más recomendable es realizar la transferencia bancaria, ya que deja constancia documental del pago. También son válidos el ingreso en cuenta, el pago por Bizum o la domiciliación bancaria.</li><li><strong>Justificante de pago:</strong> El inquilino tiene derecho a solicitar un justificante de pago (recibo) al arrendador. Es recomendable conservar todos los justificantes durante al menos 3-5 años.</li><li><strong>Factura electrónica:</strong> Si el arrendador es profesional o empresa, debe emitir factura electrónica o en papel. El inquilino puede solicitarla expresamente.</li></ul><p>En SpotStay, gestionamos los pagos de forma segura y automatizada, manteniendo un historial completo de todas las transacciones para tu tranquilidad.</p>',
                        'destacado' => true,
                        'orden_faq' => 3,
                    ],
                    [
                        'titulo' => '¿Qué hacer ante un impago del alquiler?',
                        'contenido' => '<p>El impago del alquiler es una de las situaciones más delicadas en una relación arrendaticia. Tanto inquilinos como arrendadores deben conocer sus derechos y obligaciones:</p><p><strong>Para el inquilino:</strong></p><ul><li>Si prevés que no vas a poder pagar, <strong>comunícate con el arrendador lo antes posible</strong>. Muchas veces se puede llegar a un acuerdo de pago fraccionado.</li><li>En caso de problemas económicos sobrevenidos, puedes solicitar ayudas al alquiler en tu comunidad autónoma.</li><li>Ignorar la situación solo empeorará las consecuencias legales.</li></ul><p><strong>Para el arrendador:</strong></p><ul><li>Ante el primer impago, envía un requerimiento de pago fehaciente (burofax o similar).</li><li>Si el impago persiste, puedes iniciar un procedimiento de desahucio por falta de pago, que es más rápido que otras vías judiciales.</li><li>El plazo mínimo para poder demandar es de <strong>1 mes de impago</strong>.</li></ul><p>En SpotStay ofrecemos herramientas de seguimiento de pagos y alertas tempranas para evitar que un impago puntual se convierta en un problema mayor.</p>',
                    ],
                    [
                        'titulo' => 'Fianza del alquiler: todo lo que debes saber',
                        'contenido' => '<p>La fianza es una garantía económica que el inquilino entrega al arrendador al inicio del contrato. Estos son los aspectos clave:</p><ul><li><strong>Importe:</strong> La LAU establece que la fianza equivale a <strong>una mensualidad de renta</strong> para contratos de vivienda habitual. Para otros usos (local comercial, temporada), las partes pueden acordar un importe distinto.</li><li><strong>Depósito obligatorio:</strong> El arrendador está obligado a depositar la fianza en el organismo público correspondiente de su comunidad autónoma (IVIMA, INCASÒL, etc.) en un plazo de 15-30 días desde la firma del contrato.</li><li><strong>Actualización:</strong> Si la renta se actualiza anualmente, la fianza también debe actualizarse en la misma proporción. El inquilino debe entregar la diferencia o el arrendador devolverla según corresponda.</li><li><strong>Devolución:</strong> Al finalizar el contrato, el arrendador debe devolver la fianza en un plazo máximo de 30 días, descontando únicamente los importes justificados por daños o deudas pendientes.</li><li><strong>Garantías adicionales:</strong> El arrendador puede solicitar garantías complementarias (aval bancario, seguro de impago, avalista personal), pero no puede exigir más de dos mensualidades adicionales como fianza extra.</li></ul><p>Si el arrendador no deposita la fianza, el inquilino puede reclamar y, en algunas comunidades, el arrendador puede enfrentarse a sanciones administrativas.</p>',
                    ],
                    [
                        'titulo' => '¿Cómo se actualiza la renta? IPC y nuevo índice',
                        'contenido' => '<p>La actualización anual de la renta del alquiler es un derecho del arrendador que debe ejercerse conforme a la ley:</p><p><strong>Métodos de actualización:</strong></p><ul><li><strong>IPC (Índice de Precios al Consumo):</strong> Históricamente el método más utilizado. La renta se actualiza según la variación del IPC interanual.</li><li><strong>IGC (Índice de Garantía de Competitividad):</strong> Alternativa al IPC que solía dar valores más moderados.</li><li><strong>Nuevo Índice de Referencia (2025 en adelante):</strong> Creado por la Ley de Vivienda 2023, con el objetivo de que las subidas sean más moderadas y predecibles.</li></ul><p><strong>Normas importantes:</strong></p><ul><li>La actualización solo puede aplicarse una vez al año, en la fecha pactada en el contrato.</li><li>Debe comunicarse por escrito al inquilino con al menos <strong>30 días de antelación</strong>.</li><li>Si no se comunica en el plazo establecido, se pierde el derecho a actualizar ese año.</li><li>La Ley de Vivienda 2023 estableció topes temporales a la subida (2% en 2023, 3% en 2024).</li></ul><p>En SpotStay, la actualización de la renta se calcula automáticamente según el índice acordado, evitando errores y facilitando la comunicación entre las partes.</p>',
                    ],
                    [
                        'titulo' => 'Morosidad en el alquiler: consecuencias y cómo evitarla',
                        'contenido' => '<p>La morosidad es uno de los mayores problemas en el mercado del alquiler, tanto para arrendadores como para inquilinos de buena fe:</p><p><strong>Consecuencias para el inquilino moroso:</strong></p><ul><li>Acumulación de deuda con intereses de demora (normalmente el interés legal del dinero).</li><li>Entrada en ficheros de morosidad (ASNEF, RAI) que dificultarán futuros alquileres o créditos.</li><li>Procedimiento de desahucio con condena en costas.</li><li>Imposibilidad de acceder a ayudas al alquiler.</li></ul><p><strong>Cómo prevenirlo:</strong></p><ul><li><strong>Para arrendadores:</strong> Exigir un estudio de solvencia, solicitar aval o seguro de impago, mantener una comunicación fluida con el inquilino.</li><li><strong>Para inquilinos:</strong> Ser realista con el presupuesto mensual, priorizar el pago del alquiler, comunicar cualquier dificultad económica con antelación.</li></ul><p>SpotStay incluye herramientas de análisis de solvencia y alertas preventivas para reducir el riesgo de morosidad en tus alquileres.</p>',
                    ],
                ],
            ],
            [
                'nombre' => 'Incidencias y reparaciones',
                'icono' => 'bi bi-wrench-adjustable',
                'orden' => 4,
                'articulos' => [
                    [
                        'titulo' => '¿Quién se hace cargo de las reparaciones?',
                        'contenido' => '<p>Una de las preguntas más frecuentes en el día a día del alquiler es quién debe pagar las reparaciones. La ley establece una clara distinción:</p><p><strong>Reparaciones a cargo del arrendador:</strong></p><ul><li>Reparaciones necesarias para mantener la vivienda en condiciones habitables (averías estructurales, tuberías generales, instalación eléctrica, caldera, etc.).</li><li>El arrendador está obligado a realizar estas reparaciones <strong>sin que pueda elevar la renta</strong> por ello.</li><li>Si la reparación es urgente (pérdida de agua, avería eléctrica grave), el inquilino puede realizarla y luego reclamar el importe al arrendador, siempre que justifique la urgencia.</li></ul><p><strong>Reparaciones a cargo del inquilino:</strong></p><ul><li>El mantenimiento diario y las pequeñas reparaciones por desgaste normal de uso (bombillas, pequeños arreglos de fontanería, pintura, etc.).</li><li>Las reparaciones derivadas de un mal uso de la vivienda por parte del inquilino.</li></ul><p>Es recomendable que el contrato especifique claramente los límites de responsabilidad de cada parte para evitar malentendidos.</p>',
                        'destacado' => true,
                        'orden_faq' => 4,
                    ],
                    [
                        'titulo' => '¿Cómo reportar una avería urgente?',
                        'contenido' => '<p>Las averías urgentes requieren una actuación rápida para evitar daños mayores. Desde SpotStay te recomendamos seguir estos pasos:</p><ol><li><strong>Identifica el tipo de avería:</strong> ¿Es una emergencia real? (fuga de gas, inundación, avería eléctrica grave) o ¿puede esperar unas horas?</li><li><strong>Contacta con los servicios de emergencia si es necesario:</strong> Para fugas de gas (900 100 147) o emergencias médicas (112).</li><li><strong>Notifica la incidencia al arrendador o al gestor</strong> a través de la plataforma SpotStay, indicando claramente el problema y si es urgente.</li><li><strong>Documenta la avería:</strong> Toma fotos y vídeos del problema, fechados si es posible.</li><li><strong>Si es una emergencia y no puedes contactar con nadie:</strong> Puedes contratar un servicio urgente y reclamar posteriormente el importe, guardando todas las facturas y justificantes.</li></ol><p>En SpotStay, las incidencias urgentes tienen un sistema de priorización automática para que el gestor o arrendador reciban una alerta inmediata.</p>',
                    ],
                    [
                        'titulo' => 'Plazos máximos para reparaciones según la ley',
                        'contenido' => '<p>Aunque la LAU no establece plazos concretos para cada tipo de reparación, la jurisprudencia y las buenas prácticas del sector recomiendan los siguientes plazos máximos:</p><ul><li><strong>Averías urgentes (agua, gas, electricidad):</strong> 24-48 horas. Si afectan a la habitabilidad básica, el plazo es inmediato.</li><li><strong>Reparaciones de electrodomésticos (nevera, caldera, vitrocerámica):</strong> 5-7 días hábiles.</li><li><strong>Reparaciones de fontanería no urgente:</strong> 7-15 días.</li><li><strong>Reparaciones de carpintería (puertas, ventanas, persianas):</strong> 10-15 días.</li><li><strong>Reparaciones estructurales (humedades, grietas, filtraciones):</strong> 15-30 días, dependiendo de la complejidad.</li></ul><p>Si el arrendador no realiza la reparación en un plazo razonable, el inquilino puede:</p><ol><li>Solicitar una reducción proporcional de la renta.</li><li>Realizar la reparación y reclamar el importe.</li><li>En casos graves, rescindir el contrato.</li></ol>',
                    ],
                    [
                        'titulo' => 'Responsabilidad por daños: inquilino vs. propietario',
                        'contenido' => '<p>Determinar quién es responsable de los daños en la vivienda alquilada puede ser complejo. Aquí tienes una guía práctica:</p><p><strong>Daños imputables al inquilino:</strong></p><ul><li>Rotura de cristales, electrodomésticos por mal uso.</li><li>Manchas o daños en paredes por golpes o descuidos.</li><li>Atascos por tirar objetos inadecuados por el desagüe.</li><li>Daños por no haber realizado el mantenimiento básico (como limpiar la caldera).</li></ul><p><strong>Daños imputables al arrendador:</strong></p><ul><li>Averías por antigüedad o desgaste normal (tuberías oxidadas, caldera que deja de funcionar, persianas que se rompen por el uso).</li><li>Problemas estructurales (humedades por filtración, grietas en fachada).</li><li>Defectos de construcción o instalación.</li></ul><p><strong>Daños por caso fortuito o fuerza mayor:</strong></p><ul><li>Normalmente los cubre el seguro de hogar. Es recomendable que tanto arrendador como inquilino tengan sus respectivos seguros.</li></ul><p>La mejor forma de evitar conflictos es realizar un <strong>inventario detallado con fotos</strong> al inicio y al final del contrato, documentando el estado de la vivienda.</p>',
                    ],
                    [
                        'titulo' => 'Emergencias en la vivienda: ¿qué hacer?',
                        'contenido' => '<p>Ante una emergencia en la vivienda alquilada, mantén la calma y sigue estos pasos:</p><p><strong>1. Emergencias con riesgo para personas:</strong></p><ul><li>Fuga de gas: No enciendas luces ni electrodomésticos, abre ventanas, cierra la llave de paso y llama al 900 100 147 (emergencias gas) o al 112.</li><li>Incendio: Sal de la vivienda, cierra puertas y ventanas, llama al 112. No uses el ascensor.</li><li>Inundación grave: Corta el agua (llave de paso general), desconecta la electricidad si hay riesgo y retira objetos de valor.</li></ul><p><strong>2. Emergencias materiales:</strong></p><ul><li>Avería eléctrica general: Verifica si es solo en tu vivienda (baja el ICP) o en todo el edificio (avisa al presidente de la comunidad).</li><li>Rotura de tubería mayor: Corta el agua y contacta con un fontanero urgente. Notifica al arrendador inmediatamente.</li></ul><p><strong>3. Después de la emergencia:</strong></p><ul><li>Documenta todo con fotos y vídeos.</li><li>Notifica la incidencia a través de SpotStay con todos los detalles.</li><li>Conserva facturas de cualquier servicio urgente que hayas tenido que contratar.</li><li>Contacta con tu seguro de hogar si es necesario.</li></ul><p>En SpotStay, las emergencias se marcan con prioridad máxima para que el gestor actúe de inmediato.</p>',
                    ],
                ],
            ],
            [
                'nombre' => 'Vivienda y uso del inmueble',
                'icono' => 'bi bi-house',
                'orden' => 5,
                'articulos' => [
                    [
                        'titulo' => 'Normas de convivencia en la comunidad de vecinos',
                        'contenido' => '<p>La convivencia en una comunidad de propietarios está regulada por la Ley de Propiedad Horizontal y por los estatutos de la comunidad:</p><ul><li><strong>Obligaciones del inquilino:</strong> El inquilino debe cumplir las mismas normas de convivencia que el propietario: respetar los horarios de descanso, no realizar actividades molestas, usar correctamente las zonas comunes.</li><li><strong>Horario de descanso:</strong> Generalmente de 22:00 a 08:00, aunque puede variar según los estatutos de cada comunidad.</li><li><strong>Uso de zonas comunes:</strong> Piscina, gimnasio, salón de eventos, trasteros, etc. Deben usarse según la normativa de la comunidad.</li><li><strong>Obras en la vivienda:</strong> El inquilino no puede realizar obras que afecten a la estructura o a elementos comunes sin autorización del arrendador y de la comunidad.</li><li><strong>Responsabilidad por daños:</strong> El inquilino responde ante la comunidad por los daños que cause en las zonas comunes.</li></ul><p>Si surgen conflictos de convivencia, lo recomendable es intentar primero una mediación entre las partes antes de elevar el asunto a la junta de propietarios o a la vía judicial.</p>',
                    ],
                    [
                        'titulo' => 'Subarriendo: ¿puedo realquilar la vivienda?',
                        'contenido' => '<p>El subarriendo consiste en ceder parte o la totalidad de la vivienda alquilada a un tercero. La LAU regula esta figura de la siguiente manera:</p><ul><li><strong>Subarriendo parcial:</strong> El inquilino puede subarrendar parte de la vivienda (una habitación) siempre que cuente con <strong>autorización expresa y por escrito del arrendador</strong>.</li><li><strong>Subarriendo total:</strong> No está permitido sin autorización expresa del arrendador. Ceder la totalidad de la vivienda sin permiso puede ser causa de rescisión del contrato.</li><li><strong>Precio del subarriendo:</strong> El precio del subarriendo no puede ser superior a la renta proporcional que paga el inquilino principal, salvo que se acuerde otra cosa.</li><li><strong>Plataformas turísticas (Airbnb, Booking):</strong> El alquiler turístico de la vivienda completa sin permiso del arrendador está expresamente prohibido en la mayoría de los contratos y puede ser causa de desahucio.</li></ul><p>Si estás pensando en compartir piso o alquilar una habitación, asegúrate de revisar tu contrato y obtener el consentimiento por escrito del arrendador para evitar problemas legales.</p>',
                    ],
                    [
                        'titulo' => 'Mascotas en pisos de alquiler',
                        'contenido' => '<p>La tenencia de mascotas en viviendas alquiladas ha sido tradicionalmente un punto conflictivo. Con la reciente jurisprudencia y la Ley de Vivienda 2023, la situación ha cambiado:</p><ul><li><strong>Prohibición genérica:</strong> Las cláusulas que prohíben de forma absoluta la tenencia de mascotas pueden ser consideradas abusivas si no existe una razón objetiva que lo justifique.</li><li><strong>Razones válidas para prohibir:</strong> Alergias documentadas del arrendador o de otros inquilinos, normativa de la comunidad de propietarios que lo prohíba expresamente (aunque esto es cada vez menos frecuente), o que la vivienda sea manifiestamente inadecuada para albergar mascotas.</li><li><strong>Responsabilidad del inquilino:</strong> Aunque tengas mascota, eres responsable de los daños que pueda causar y de mantener unas condiciones de higiene adecuadas.</li><li><strong>Garantía adicional:</strong> El arrendador puede solicitar una garantía complementaria o un seguro de responsabilidad civil que cubra posibles daños causados por la mascota.</li></ul><p>Lo más recomendable es negociar la tenencia de mascotas al inicio del contrato y dejar constancia por escrito del acuerdo alcanzado.</p>',
                    ],
                    [
                        'titulo' => 'Modificaciones y obras en la vivienda alquilada',
                        'contenido' => '<p>Como inquilino, puedes tener la tentación de hacer cambios en la vivienda para hacerla más cómoda. Sin embargo, hay ciertas limitaciones:</p><p><strong>Obras que NO necesitan autorización:</strong></p><ul><li>Cambios estéticos menores: cuadros, estanterías que no requieran taladrar, vinilos decorativos, etc.</li><li>Siempre que no dañen la pared y sean reversibles.</li></ul><p><strong>Obras que SÍ necesitan autorización del arrendador:</strong></p><ul><li>Taladrar paredes para instalar muebles o soportes.</li><li>Cambiar la pintura de las paredes (aunque algunas comunidades autónomas permiten pintar siempre que se devuelva al color original).</li><li>Cambiar suelos, puertas, ventanas o electrodomésticos.</li><li>Instalar aire acondicionado, toldos o antenas.</li><li>Cualquier obra que afecte a la estructura del edificio.</li></ul><p><strong>Importante:</strong> Si realizas obras sin autorización, el arrendador puede exigirte que devuelvas la vivienda a su estado original al finalizar el contrato, con los costes que ello conlleve.</p>',
                    ],
                    [
                        'titulo' => 'Suministros: agua, luz y gas en el alquiler',
                        'contenido' => '<p>La gestión de los suministros es uno de los aspectos prácticos más importantes del alquiler:</p><p><strong>¿A nombre de quién van los suministros?</strong></p><ul><li>Lo más habitual es que cada suministro vaya a nombre de quien lo usa. Si el inquilino paga los consumos, los contratos deben estar a su nombre.</li><li>Si los suministros están a nombre del arrendador, el inquilino debe pagarle mensualmente la parte proporcional de los consumos, preferiblemente con una estimación realista.</li></ul><p><strong>Altas y bajas:</strong></p><ul><li>Al inicio del contrato, el inquilino debe dar de alta los suministros a su nombre si así se acordó.</li><li>Al finalizar el contrato, debe darles de baja o ponerlos a nombre del arrendador.</li><li>Los costes de alta/baja suelen ser por cuenta del inquilino.</li></ul><p><strong>Gastos de comunidad:</strong></p><ul><li>Salvo que el contrato especifique lo contrario, los gastos de comunidad ordinarios son por cuenta del arrendador. Si el contrato los imputa al inquilino, debe hacerse de forma expresa.</li></ul><p>En SpotStay, puedes gestionar los recibos de suministros y mantener un registro organizado de todos los pagos asociados a la vivienda.</p>',
                    ],
                    [
                        'titulo' => 'Empadronamiento en la vivienda alquilada',
                        'contenido' => '<p>El empadronamiento es un derecho y una obligación de toda persona que reside en un municipio español. Como inquilino, tienes derecho a empadronarte en la vivienda que alquilas:</p><ul><li><strong>No necesitas permiso del arrendador:</strong> El empadronamiento es un trámite administrativo que no requiere autorización del propietario. El arrendador no puede prohibirte empadronarte.</li><li><strong>Documentación necesaria:</strong> Normalmente se requiere el contrato de alquiler y el DNI/NIE. En algunos ayuntamientos también piden un certificado de convivencia o un recibo de suministro reciente.</li><li><strong>Si el arrendador no te da el contrato:</strong> Puedes empadronarte con otros documentos que acrediten tu residencia (recibos de suministros, testigos, etc.).</li><li><strong>¿Afecta al arrendador?</strong> El empadronamiento no tiene consecuencias fiscales negativas para el arrendador. Simplemente acredita que resides en ese domicilio.</li></ul><p>El empadronamiento es necesario para acceder a servicios públicos como la tarjeta sanitaria, la escolarización de hijos o determinadas ayudas y prestaciones sociales.</p>',
                    ],
                ],
            ],
            [
                'nombre' => 'Finalización del contrato',
                'icono' => 'bi bi-door-open',
                'orden' => 6,
                'articulos' => [
                    [
                        'titulo' => 'Preaviso: plazos para comunicar la salida',
                        'contenido' => '<p>Cuando se acerca el final del contrato de alquiler, es importante respetar los plazos de preaviso establecidos:</p><p><strong>Si NO deseas renovar (inquilino):</strong></p><ul><li>Debes comunicarlo al arrendador con al menos <strong>30 días de antelación</strong> a la fecha de finalización del contrato o de la prórroga en curso.</li><li>Si no lo haces, el contrato se prorrogará automáticamente por un año más.</li></ul><p><strong>Si NO deseas renovar (arrendador):</strong></p><ul><li>Durante los primeros 5/7 años, el arrendador no puede negarse a la prórroga salvo causas justificadas (necesidad de vivienda propia, obras mayores).</li><li>Una vez superado el período mínimo, debe comunicarlo con al menos <strong>30 días de antelación</strong> si no desea renovar.</li></ul><p><strong>Preaviso durante el primer año:</strong> Si el inquilino quiere irse antes de cumplir el primer año, debe indemnizar al arrendador con una mensualidad por cada año que falte por cumplir.</p><p>El preaviso debe hacerse por escrito (email, burofax o carta certificada) para dejar constancia de la comunicación.</p>',
                    ],
                    [
                        'titulo' => 'Devolución de llaves: procedimiento y documento',
                        'contenido' => '<p>La entrega de llaves es el acto formal que marca el final efectivo del contrato de alquiler. Te recomendamos seguir este procedimiento:</p><ol><li><strong>Acordar una fecha y hora</strong> para la entrega de llaves con el arrendador o gestor.</li><li><strong>Realizar una inspección conjunta</strong> de la vivienda, documentando el estado final con fotos y vídeos.</li><li><strong>Firmar un documento de entrega de llaves</strong> que incluya: fecha y hora de entrega, estado general de la vivienda, lectura de contadores, y cualquier observación relevante.</li><li><strong>Entregar todos los juegos de llaves,</strong> incluyendo las de la vivienda, portal, buzón, trastero o garaje si aplica.</li><li><strong>Cancelar los suministros</strong> a tu nombre (agua, luz, gas) o ponerlos a nombre del arrendador si así se acordó.</li></ol><p>El documento de entrega de llaves es importante porque determina el momento a partir del cual dejas de pagar la renta y comienza el plazo de 30 días para la devolución de la fianza.</p>',
                    ],
                    [
                        'titulo' => 'Devolución de la fianza: plazos y deducciones',
                        'contenido' => '<p>La devolución de la fianza es uno de los momentos más delicados al finalizar un contrato de alquiler. Estos son tus derechos:</p><p><strong>Plazo legal:</strong> El arrendador tiene <strong>30 días</strong> desde la entrega de llaves para devolver la fianza al inquilino. Si no lo hace en ese plazo, puede incurrir en mora.</p><p><strong>Deducciones permitidas:</strong></p><ul><li>Deudas pendientes de renta o suministros.</li><li>Daños en la vivienda documentados (con fotos de antes y después) que excedan el desgaste normal por uso.</li><li>Faltantes de mobiliario o electrodomésticos que estaban presentes al inicio (según el inventario firmado).</li></ul><p><strong>Deducciones NO permitidas:</strong></p><ul><li>Desgaste normal por el uso de la vivienda (paredes que necesitan pintura, alfombras gastadas, etc.).</li><li>Mejoras que el arrendador decide hacer después de la marcha del inquilino (pintar toda la casa, cambiar la cocina, etc.).</li><li>Gastos de administración o gestión no acordados previamente.</li></ul><p>Si el arrendador no devuelve la fianza sin justificación, el inquilino puede reclamar judicialmente, pudiendo obtener además intereses de demora.</p>',
                        'destacado' => true,
                        'orden_faq' => 5,
                    ],
                    [
                        'titulo' => 'Inspección final de la vivienda: checklist',
                        'contenido' => '<p>La inspección final de la vivienda es el momento de verificar que todo está en orden. Te recomendamos revisar esta lista:</p><p><strong>Antes de la inspección:</strong></p><ul><li>Limpia a fondo la vivienda (debe estar en condiciones similares a cuando entraste).</li><li>Repara pequeños daños que puedas haber causado (agujeros de cuadros, etc.).</li><li>Retira todos tus muebles y pertenencias.</li></ul><p><strong>Durante la inspección (revisar con el arrendador):</strong></p><ul><li>✅ Paredes y techos: sin golpes, manchas ni humedades nuevas.</li><li>✅ Suelos: sin roturas, manchas permanentes o desgaste anormal.</li><li>✅ Carpintería: puertas, ventanas y persianas funcionando correctamente.</li><li>✅ Fontanería: grifos sin fugas, WC e inodoro funcionando, desagües sin atasco.</li><li>✅ Electricidad: todos los enchufes e interruptores funcionan.</li><li>✅ Electrodomésticos: funcionan correctamente y están limpios.</li><li>✅ Mobiliario (si aplica): según inventario, sin roturas.</li><li>✅ Tomas de antena/teléfono/internet: operativas.</li><li>✅ Lectura de contadores: agua, luz y gas (anotar lecturas finales).</li></ul><p>Documenta todo con fotos y firma el acta de entrega con el arrendador. Una inspección bien hecha evita conflictos posteriores sobre la fianza.</p>',
                    ],
                ],
            ],
            [
                'nombre' => 'Conflictos y reclamaciones',
                'icono' => 'bi bi-exclamation-triangle',
                'orden' => 7,
                'articulos' => [
                    [
                        'titulo' => '¿Qué hacer ante un conflicto con el arrendador?',
                        'contenido' => '<p>Los conflictos en el alquiler son desagradables pero, lamentablemente, no infrecuentes. Aquí tienes una guía de actuación progresiva:</p><p><strong>1. Comunicación directa:</strong> Muchos conflictos se resuelven con una conversación tranquila. Expón tu problema por escrito (email o mensaje en SpotStay) y propón una solución razonable.</p><p><strong>2. Mediación:</strong> Si la comunicación directa no funciona, acude a un servicio de mediación. Muchas comunidades autónomas ofrecen servicios gratuitos de mediación en conflictos de vivienda. También puedes recurrir a un mediador privado.</p><p><strong>3. Reclamación administrativa:</strong> Puedes presentar una reclamación ante la Agencia de Vivienda de tu comunidad autónoma si consideras que se han vulnerado tus derechos.</p><p><strong>4. Vía judicial:</strong> Como último recurso, puedes acudir a los tribunales. Para reclamaciones de hasta 2.000 € no es necesario abogado ni procurador. Por encima de esa cantidad, sí será obligatorio.</p><p><strong>5. Asesoramiento legal:</strong> Antes de dar cualquier paso legal, consulta con un abogado especializado en arrendamientos. En SpotStay podemos orientarte sobre los primeros pasos a seguir.</p><p>Recuerda: la vía judicial debe ser siempre el último recurso. Intenta agotar antes todas las vías de diálogo y mediación.</p>',
                    ],
                    [
                        'titulo' => 'Procedimiento de desahucio: tipos y plazos',
                        'contenido' => '<p>El desahucio es un procedimiento judicial mediante el cual el arrendador recupera la posesión de la vivienda. Existen varios tipos:</p><p><strong>1. Desahucio por falta de pago:</strong></p><ul><li>Es el más común. Se inicia cuando el inquilino deja de pagar la renta.</li><li>Plazo: Desde el primer mes de impago se puede iniciar el procedimiento.</li><li>Duración estimada: 2-4 meses si el inquilino no se opone, hasta 6-12 meses si hay oposición.</li></ul><p><strong>2. Desahucio por expiración del plazo:</strong></p><ul><li>Cuando el contrato ha finalizado y el inquilino no entrega la vivienda.</li><li>Es más rápido que el de impago si no hay prórroga forzosa.</li></ul><p><strong>3. Desahucio por causa grave:</strong></p><ul><li>Por actividades molestas, ilegales, subarriendo no consentido, daños graves, etc.</li><li>Requiere acreditar la causa ante el juez.</li></ul><p><strong>Protección de inquilinos vulnerables:</strong> La Ley de Vivienda 2023 establece mecanismos de protección para inquilinos en situación de vulnerabilidad, pudiendo suspenderse el desahucio en determinadas circunstancias si se acredita dicha situación.</p><p>Si estás en riesgo de desahucio, busca asesoramiento legal inmediato. Existen recursos y ayudas públicas para evitar la pérdida de la vivienda.</p>',
                    ],
                    [
                        'titulo' => 'Reclamación de cantidades impagadas',
                        'contenido' => '<p>Cuando un inquilino acumula deudas por impago de rentas o suministros, el arrendador puede reclamar las cantidades adeudadas. Estos son los pasos a seguir:</p><p><strong>Fase extrajudicial:</strong></p><ol><li><strong>Requerimiento de pago:</strong> Envía un escrito fehaciente (burofax o carta certificada con acuse de recibo) detallando las cantidades adeudadas y concediendo un plazo para el pago (normalmente 10 días).</li><li><strong>Negociación:</strong> Ofrece opciones de pago fraccionado si crees que el inquilino puede ponerse al día.</li></ol><p><strong>Fase judicial:</strong></p><ol><li><strong>Demanda de desahucio por impago:</strong> Acumula la acción de desahucio con la reclamación de rentas impagadas. Es la vía más rápida y eficaz.</li><li><strong>Procedimiento monitorio:</strong> Si solo quieres reclamar la deuda sin recuperar la vivienda, o si el inquilino ya ha abandonado la vivienda.</li></ol><p><strong>Cuantías reclamables:</strong></p><ul><li>Rentas impagadas.</li><li>Intereses de demora (el interés legal del dinero, salvo que el contrato establezca otro).</li><li>Costas judiciales si el inquilino es condenado.</li></ul><p>En SpotStay, cada impago registra automáticamente un historial detallado que facilita la posterior reclamación judicial si fuera necesario.</p>',
                    ],
                    [
                        'titulo' => 'Mediación como alternativa a la vía judicial',
                        'contenido' => '<p>La mediación es un método alternativo de resolución de conflictos que puede evitar largos y costosos procesos judiciales:</p><p><strong>Ventajas de la mediación:</strong></p><ul><li><strong>Más rápida:</strong> Las sesiones de mediación pueden completarse en semanas, no meses.</li><li><strong>Más económica:</strong> Mucho más barata que un proceso judicial.</li><li><strong>Voluntaria:</strong> Ambas partes deben aceptar voluntariamente la mediación.</li><li><strong>Confidencial:</strong> Lo tratado en mediación no puede usarse en un juicio posterior.</li><li><strong>Preserva la relación:</strong> Busca soluciones consensuadas que ambas partes acepten.</li></ul><p><strong>¿Cuándo es recomendable la mediación?</strong></p><ul><li>Conflictos sobre reparaciones y mantenimiento.</li><li>Desacuerdos sobre la fianza.</li><li>Problemas de convivencia.</li><li>Interpretación de cláusulas del contrato.</li></ul><p><strong>¿Dónde acudir?</strong></p><ul><li>Servicios de mediación de las comunidades autónomas (muchos son gratuitos).</li><li>Mediadores privados especializados en vivienda.</li><li>Colegios de abogados (ofrecen servicios de mediación).</li></ul><p>Desde SpotStay, creemos en el diálogo como primera herramienta para resolver conflictos. Nuestra plataforma facilita la comunicación directa entre las partes como paso previo a cualquier otra medida.</p>',
                    ],
                ],
            ],
            [
                'nombre' => 'Seguros y responsabilidad',
                'icono' => 'bi bi-shield-check',
                'orden' => 8,
                'articulos' => [
                    [
                        'titulo' => '¿Es obligatorio tener seguro de hogar en un alquiler?',
                        'contenido' => '<p>La contratación de un seguro de hogar no es obligatoria por ley para el inquilino ni para el arrendador, pero es <strong>altamente recomendable</strong> para ambas partes:</p><p><strong>Para el arrendador (seguro del propietario):</strong></p><ul><li>Cubre los daños estructurales del inmueble (incendio, explosión, rotura de tuberías, fenómenos meteorológicos, etc.).</li><li>Muchas comunidades de propietarios exigen que cada vivienda tenga un seguro mínimo de responsabilidad civil.</li><li>Si hay hipoteca, el banco suele exigir un seguro de hogar.</li></ul><p><strong>Para el inquilino (seguro de contenidos):</strong></p><ul><li>Cubre tus pertenencias personales (muebles, ropa, electrónica, etc.) ante robo, incendio o daños por agua.</li><li>Incluye responsabilidad civil por daños que puedas causar a la comunidad o a terceros (por ejemplo, una inundación que afecte al vecino de abajo).</li><li>Es relativamente económico (desde 50-80 €/año) y ofrece una tranquilidad muy valiosa.</li></ul><p><strong>¿Puede el arrendador exigir un seguro?</strong> Sí, el contrato puede incluir una cláusula que obligue al inquilino a contratar un seguro de hogar (contenidos + responsabilidad civil). En ese caso, es obligatorio.</p>',
                    ],
                    [
                        'titulo' => 'Responsabilidad civil en el alquiler',
                        'contenido' => '<p>La responsabilidad civil en el contexto de un alquiler se refiere a la obligación de reparar los daños causados a terceros. Estos son los escenarios más comunes:</p><p><strong>Daños causados por el inquilino:</strong></p><ul><li>Inundación al vecino de abajo por dejar el grifo abierto o por una rotura de tubería por mal uso.</li><li>Incendio provocado por una vela, un cigarro o un electrodoméstico defectuoso propiedad del inquilino.</li><li>Daños en zonas comunes del edificio (portal, ascensor, garaje).</li></ul><p><strong>Daños causados por el arrendador:</strong></p><ul><li>Vicios ocultos de la vivienda que causen daños al inquilino (por ejemplo, una instalación eléctrica defectuosa que provoca un incendio).</li><li>Caídas o accidentes por mal estado de elementos comunes.</li></ul><p><strong>Cobertura recomendada:</strong> Un seguro de responsabilidad civil con una cobertura mínima de 300.000 € es suficiente para la mayoría de los casos. Muchos seguros de hogar ya incluyen esta cobertura.</p>',
                    ],
                    [
                        'titulo' => 'Daños en la vivienda: ¿cubre el seguro?',
                        'contenido' => '<p>No todos los daños están cubiertos por el seguro de hogar. Aquí tienes una guía práctica:</p><p><strong>Daños que SÍ suele cubrir el seguro:</strong></p><ul><li>Incendio, explosión, rayos.</li><li>Daños por agua (rotura de tuberías, escapes, heladas).</li><li>Daños eléctricos (sobrecarga, cortocircuito).</li><li>Rotura de cristales (depende de la póliza).</li><li>Robo con fuerza (contenidos, hasta el límite de la póliza).</li><li>Responsabilidad civil (daños a terceros).</li></ul><p><strong>Daños que NO suele cubrir el seguro:</strong></p><ul><li>Desgaste por uso normal de la vivienda.</li><li>Daños por falta de mantenimiento (tuberías obstruidas por falta de limpieza, caldera sin revisar).</li><li>Daños causados intencionadamente.</li><li>Pérdidas por vicios constructivos previos.</li><li>Bienes de especial valor (joyas, obras de arte) sin declaración expresa.</li></ul><p>Revisa siempre las condiciones particulares de tu póliza, ya que cada aseguradora tiene sus propias coberturas y exclusiones.</p>',
                    ],
                    [
                        'titulo' => 'Seguro de impago de alquiler: protección para el arrendador',
                        'contenido' => '<p>El seguro de impago de alquiler es una herramienta cada vez más utilizada por los arrendadores para protegerse frente al riesgo de morosidad:</p><p><strong>¿Qué cubre?</strong></p><ul><li>El pago de las rentas impagadas durante un período determinado (normalmente 6-12 meses).</li><li>Los gastos legales del procedimiento de desahucio (abogado, procurador, tasas judiciales).</li><li>En algunos casos, la defensa jurídica del arrendador ante cualquier conflicto derivado del contrato.</li><li>Daños en la vivienda causados por el inquilino (con límites).</li></ul><p><strong>¿Cuánto cuesta?</strong> Entre el 3% y el 5% de la renta anual, dependiendo del perfil del inquilino y de las coberturas contratadas.</p><p><strong>Requisitos habituales:</strong></p><ul><li>El inquilino debe pasar un estudio de solvencia (la aseguradora lo realiza).</li><li>La vivienda debe cumplir ciertos estándares de habitabilidad.</li><li>El contrato debe estar registrado si la comunidad autónoma lo exige.</li></ul><p>En SpotStay, ofrecemos integración con aseguradoras para facilitar la contratación de este seguro directamente desde la plataforma.</p>',
                    ],
                ],
            ],
            [
                'nombre' => 'Fiscalidad (arrendadores)',
                'icono' => 'bi bi-receipt',
                'orden' => 9,
                'articulos' => [
                    [
                        'titulo' => '¿Cómo tributan los ingresos por alquiler en el IRPF?',
                        'contenido' => '<p>Los ingresos obtenidos por el alquiler de una vivienda se declaran como rendimientos del capital inmobiliario en el IRPF. Estos son los aspectos clave:</p><p><strong>Declaración obligatoria:</strong> Todos los ingresos por alquiler deben declararse, independientemente de su cuantía. No declararlos puede conllevar sanciones de Hacienda.</p><p><strong>Tramos de tributación:</strong> Los rendimientos netos del alquiler se integran en la base imponible del ahorro y tributan según la escala del IRPF (19% hasta 6.000 €, 21% hasta 50.000 €, 23% hasta 200.000 €, 27% a partir de ahí).</p><p><strong>Reducción por alquiler de vivienda:</strong> Desde 2024, la reducción es del 50% del rendimiento neto positivo. Si la vivienda está en una zona de mercado tensionado y se ha firmado un nuevo contrato con una renta reducida respecto al anterior, la reducción puede llegar al 90%. Si eres menor de 35 años, la reducción puede alcanzar el 100% durante los primeros 3 años.</p><p><strong>Obligaciones formales:</strong> Como arrendador, debes expedir factura electrónica o recibo si el inquilino te lo solicita, y conservar toda la documentación de gastos e ingresos durante al menos 4 años.</p>',
                    ],
                    [
                        'titulo' => 'Gastos deducibles en el alquiler',
                        'contenido' => '<p>Como arrendador, puedes deducir una serie de gastos del rendimiento del alquiler, reduciendo así tu factura fiscal:</p><p><strong>Gastos deducibles habituales:</strong></p><ul><li><strong>Intereses de hipoteca:</strong> Los intereses de la hipoteca de la vivienda alquilada son deducibles, pero no la amortización del capital.</li><li><strong>Comunidad:</strong> Los gastos de comunidad de propietarios son deducibles.</li><li><strong>IBI (Impuesto de Bienes Inmuebles):</strong> El IBI es un gasto deducible.</li><li><strong>Seguros:</strong> Las primas de seguros de hogar, impago de alquiler y responsabilidad civil son deducibles.</li><li><strong>Reparaciones y mantenimiento:</strong> Los gastos de reparación y conservación de la vivienda son deducibles.</li><li><strong>Gastos de comunidad:</strong> Los recibos de la comunidad de propietarios.</li><li><strong>Amortización:</strong> Puedes amortizar el inmueble (3% del valor catastral del edificio) y los muebles (10% anual).</li><li><strong>Gastos de gestión:</strong> Honorarios de la agencia inmobiliaria o del gestor (como SpotStay).</li><li><strong>Suministros:</strong> Si los pagas tú como arrendador, son deducibles.</li></ul><p><strong>Importante:</strong> Debes conservar todas las facturas y justificantes de pago durante al menos 4 años para poder justificar estos gastos ante Hacienda.</p>',
                    ],
                    [
                        'titulo' => 'Declaración de ingresos por alquiler: paso a paso',
                        'contenido' => '<p>Declarar los ingresos por alquiler en la renta es un proceso sencillo si sigues estos pasos:</p><ol><li><strong>Calcula los ingresos brutos:</strong> Suma todas las rentas percibidas durante el año natural (enero a diciembre). Incluye la fianza si no la has devuelto.</li><li><strong>Suma los gastos deducibles:</strong> Reúne todas las facturas de gastos: IBI, comunidad, seguros, reparaciones, intereses de hipoteca, amortización, etc.</li><li><strong>Calcula el rendimiento neto:</strong> Ingresos brutos - gastos deducibles = rendimiento neto.</li><li><strong>Aplica la reducción:</strong> Al rendimiento neto positivo aplícale la reducción correspondiente (50% general, o el porcentaje que corresponda según tu caso).</li><li><strong>Declara en la casilla correspondiente:</strong> En la declaración de la renta, los rendimientos del capital inmobiliario se declaran en la sección de rendimientos del capital inmobiliario (casillas 3.01 a 3.17 del modelo de Renta Web de la AEAT).</li></ol><p>Si tienes dudas, SpotStay te proporciona un informe anual con todos los ingresos y gastos asociados a tus propiedades para facilitarte la declaración.</p>',
                    ],
                    [
                        'titulo' => 'Alquiler de vivienda habitual: ventajas fiscales para inquilinos',
                        'contenido' => '<p>Aunque la deducción por alquiler de vivienda habitual fue eliminada en el IRPF estatal desde 2015, aún existen deducciones autonómicas y otras ventajas:</p><p><strong>Deducciones autonómicas:</strong> Muchas comunidades autónomas mantienen deducciones propias por alquiler de vivienda habitual, con requisitos variables:</p><ul><li>Suelen estar dirigidas a menores de 35-36 años.</li><li>Se aplican sobre las cantidades pagadas por alquiler durante el año.</li><li>Los importes varían entre el 10% y el 20% de lo pagado, con límites anuales (normalmente 300-900 €).</li><li>Se requiere que la base imponible no supere ciertos límites (entre 20.000 y 30.000 € según la comunidad).</li></ul><p><strong>¿Cómo solicitarla?</strong> En tu declaración de la renta, debes identificar al arrendador con su NIF y la referencia catastral de la vivienda. Si el arrendador no declara el alquiler, Hacienda podría denegarte la deducción.</p><p><strong>Otros beneficios:</strong> Los inquilinos pueden solicitar ayudas al alquiler en sus comunidades autónomas, con cuantías que van desde 200 hasta 600 € mensuales en algunos casos.</p>',
                    ],
                ],
            ],
        ];

        foreach ($categorias as $dataCat) {
            $categoria = CategoriaArticulo::create([
                'nombre' => $dataCat['nombre'],
                'slug' => Str::slug($dataCat['nombre']),
                'icono' => $dataCat['icono'],
                'orden' => $dataCat['orden'],
                'estado' => true,
            ]);

            foreach ($dataCat['articulos'] as $i => $dataArt) {
                ArticuloAsesoria::create([
                    'id_categoria_fk' => $categoria->id,
                    'titulo' => $dataArt['titulo'],
                    'contenido' => $dataArt['contenido'],
                    'slug' => Str::slug($dataArt['titulo']),
                    'orden' => $i + 1,
                    'estado' => true,
                    'destacado' => $dataArt['destacado'] ?? false,
                    'orden_faq' => $dataArt['orden_faq'] ?? null,
                ]);
            }
        }
    }
}
